### ISSUE TITLE
As a scholar I want to browse KB data in the Media Suite using the same facets as used in Delpher, so I can use the Media Suite and Delpher in a similar way

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#104]
User story 64: I want to be able to search on specific metadata fields for newspapers: Newspaper title, article text
User story 65: I want to be able to filter my results of newspaper data on related words, publication, article type

**Comment by lilimelgar** [comment]
@wmelder Is it possible from the schema to add/name in the default facets some of the facets that are in Delpher? This helps people already familiar with Delpher to use this dataset in the MS. E.g.:
Verspreidingsgebied (of the newspaper) ->add as default facet
"Onderwerp" -> change for "Soort bericht"
Krantentitle ->add as default facet
Plaats van uitgave ->add as default facet

**Comment by jblom** [comment]
@lilimelgar I changed "Onderwerp" (tied to dc:subject) to "Soort bericht"

As to the facets (@wmelder) It seems I only can find something for the "Krantentitel" (dc:title). For "Verspreidingsgebied" and "Plaats van uitgave" I don't see any field that seems suitable or have any value. E.g. I see that dcterms_spatial, dcterms_publisher, dc:creator & dcterms_provider are all empty.

I used the kb-newspapers-test index b.t.w.

**Comment by roelandordelman** [comment]
The story of this issue should be "As a scholar I want to browse KB data in the Media Suite using the same facets as used in Delpher". 

I'm not sure why this is blocking another issue, please update.

It seems like the conclusion to this point is that it is not obvious how Delpher makes the translation from metadata fields to the "user friendly" facets. @wmelder anything to add to this?

If this is not easy to solve, I suggest to put this in the icebox.

**Comment by wmelder** [comment]
verspreidingsgebied:

"dcterms:spatial": "Regionaal/lokaal",

**Comment by jblom** [comment]
@wmelder thanks. Now I see I that indeed the dcterm:spatial is there and it is only attached to schema:Newspaper. Also I just noticed that there is also the type schema:MediaObject in there, which I did not map properly before. 

Also @lilimelgar @roelandordelman  so the KB collection is now the only collection that returns 3 different types of results: Newspapers, Articles (containing the text) and Media objects.

To make this distinction clear to the user I added a default facet (based on @type), which for now I called "Krant / Artikel / Media object" to make it clear what can be expected.

In general we have to see how users will deal with this. For this collection in particular the linked data showing on the detail page will help a lot, since you can then expect for:
1) newspaper item -> shows all articles that are part of it
2) article item -> shows the newspaper & media objects that it is part of/contains
3) media object -> shows the article it belongs to

**Comment by wmelder** [comment]
The answer of the KB on the 'plaats van uitgave':

> Bijbehorende record staat in `http://services.kb.nl/mdo/oai?verb=GetRecord&identifier=DDD:ddd:010426498:mpeg21&metadataPrefix=didl`
> 
> In de dcx staat daar `<dcterms:spatial xsi:type="dcx:creation">Achterhoek (?)</dcterms:spatial>`

**Comment by wmelder** [comment]
TODO: 
- [ ] Build an aggregated KB elastic search indexer

**Comment by jblom** [comment]
@wmelder so can we close this issue and make a new one for importing that missing field?

**Comment by wmelder** [comment]
Work to be done in issue #326
