### ISSUE TITLE
As a user, having the option to "order by title" in the search result list would make the selection of my corpus easier

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#199]
In the Single Collection and Comparative Search tools, add a third ordering option by title (alphabetical: ascendant, descendant).

**Comment by jblom** [comment]
this seemingly simple feature requires some consideration & design decisions, since each collection has zero, one or multiple title fields, so it's not obvious which field to use.

A solution could be:

1) expand the collection config with an option to assign a single title field to sort with (simple, but kind of dumb solution)
2) instead of a sort by title button, create a button where the user can select a field to sort by

in case of option 2 there are again a few things to remark:
a) you want the UI to remember which field you last selected, so the user does not have to choose the field over and over again.
b) in theory the selected sort field could be tied to the active project (session)

Finally there is currently actually something that prevents sorting by title field: ES prevents sorting by string fields and can only sort by keyword fields. For the B&G collection this means the title fields need to be reindexed with an additional keyword variant...

It seems this one has moved from simple to quite elaborate, but I'd say the options laid out here are all pretty straightforward to implement.

**Comment by lilimelgar** [comment]
As we discussed, the solution that is adopted is to use the same title value that appears in the basic metadata of the resource viewer for all records. 
The ordering function per title is needed in most cases, but mostly mostly when the user selects the search in "titles" option in the Field clusters.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #41](https://github.com/beeldengeluid/labs-search-api/issues/41) via [**ZenHub**](https://www.zenhub.com/)
