### ISSUE TITLE
Add alias to B&G aggregated index to filter per collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#202]
Change the ReIndexer to use Aliases

**Comment by wmelder** [comment]
both nisv-catalogue-radio and nisv-catalogue-tv are now available as an alias. This saves a lot of time compared to the earlier nightly reindexing process.

**Comment by roelandordelman** [comment]
@wmelder why is this in the review/QA instead of closed?

**Comment by wmelder** [comment]
This issue is about the nisv-catalogue-radio and nisv-catalogue-tv **aliases** on the nisv-catalogue-aggr **index**.
What is now realized is that 'nisv-catalogue-aggr' now also became an alias. Every night a new aggregated index is created with a postfix like '18-015' (year+day-of-the-year): 'nisv-catalogue-aggr-18-015'. After checks aliases on the 'old' index are removed, three aliases are added to the 'new' index: 'nisv-catalogue-aggr', 'nisv-catalogue-radio' and 'nisv-catalogue-tv'. The 'old' index (yesterday's one) is then removed.
This change can be tested, because the 'new' index now also contains an improved mapping (and contains all recent changes from the NISV catalogue).

**Comment by jblom** [comment]
I'd say we can close this one. This works for a while now
