### ISSUE TITLE
Get a list of Github issues using Github API

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#254]
As part of the development support team, for helping with the organization of issues in Github, I need to export all Github issues to a Json or CSV file with at least: 

-# of issue
-title of issue
-content of issue
-labels
-milestones
-assignees
-when was it created

This can be done by using the Github API: https://developer.github.com/v3/issues/#list-issues
Using this command:
curl -i https://api.github.com/repositories/68213535/issues?state=open\=all

The problem to solve in this issue is how to get all the open issues: Github only provides these results per page. How to obtain them all from all pages?

**Comment by avlisodraude** [comment]
@lilimelgar 
To get the total number of issues in GITHUB:
https://api.github.com/search/issues?q=repo:CLARIAH/wp5_mediasuite+type:issue

The first key/value pair (total_count) shows the total number of results

If you want to get only the total per state (open/closed) just add the state parameter as in:

https://api.github.com/search/issues?q=repo:CLARIAH/wp5_mediasuite+type:issue+state:open
https://api.github.com/search/issues?q=repo:CLARIAH/wp5_mediasuite+type:issue+state:closed

Since the API has a limit of 100 issues to return the more practical (temp) solution at the moment is to get it per page which can be done via :


to get the maximum of possible return via the API (which is 100)
https://api.github.com/repos/CLARIAH/wp5_mediasuite/issues?state=open&page=1&per_page=100

The API returns by default JSON data so it is only a matter of saving the page/file and it will be saved as a JSON file.

**Comment by lilimelgar** [comment]
Excellent! thanks
