### ISSUE TITLE
Change the color of visited links (search results) in the result list

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#279]
When the user clicks on a result, change the color of the link so s(he) knows that she as visited it already. This complements the issue of showing when an item has been already bookmarked (#419)

**Comment by avlisodraude** [comment]
@avlisodraude @jblom :
Issue done in branch task/#279-change-color-of-visited-links from the labo-components.
Move to Review since a main behaviour should be addressed, when to remove those links from memory (localStorage)?
Options:
- set an expiration date for the items to be removed.
- remove them when changing collection/project ?

At the moment the 'visited items' get removed once a collection is selected (as suggested by Jaap)

Looking forward for your suggestions.

**Comment by jblom** [comment]
@avlisodraude so I'd say don't expire the visited links (we could e.g. add a button to the workspace where you can clear the cache per project) and also store them per project, so you can keep track of what you've visited per project.

@lilimelgar what do you think?

**Comment by jblom** [comment]
@avlisodraude so let's not relate it to the selected project. Also expire them after a session

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :
Done and now the localstorage is not removed unless a session is ended. 
Pull request has been made too :-)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #177](https://github.com/beeldengeluid/labo-components/issues/177) via [**ZenHub**](https://www.zenhub.com/)
