### ISSUE TITLE
As a developer, I need to find out and solve the issue of some user projects not being displayed

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#283]
After testing with several users, we have detected that in some cases the user projects are not stored/displayed. The user creates a project, but it does not show in the list of User projects in the Work space.
We have tested in Mac (Chrome browser) in most cases. There is not apparent reason for this to happen, so the issue is to investigate what the problem is. [Here](https://drive.google.com/open?id=1K5eQuBeZbWPmCHKO62U1vVZVr_dNbwDT) a screencast of one case in which it does not work.

**Comment by lilimelgar** [comment]
@jblom The issue with projects not being displayed seems to be fixed. The issue that remains is that when more than 10 projects are added, the pagination does not change, and users can only see projects on Page 1. I moved this to the backlog as a "bug".

**Comment by jblom** [comment]
This is something @jwassenaarbg could fix. Paging hasn't been implemented yet in the workspace API. Also the code for paging in the labo-components (made by FW) hasn't been tested yet.

**Comment by jwassenaarbg** [comment]
The pagination works, if I set the perPage parameter in SortTable.jsx to for example "5". I get 2 pages with both 5 results. The problem is with the Elastic Search query: the size parameter is set to 10, and thus only 10 results are returned. 

I need more information to solve this bug. I can set the size parameter in Elastic Search to a larger number, for example 1000. This will retrieve up to 1000 projects. Hopefully then, nobody will have more than 1000 projects. There is no 'unlimited' option in Elastic Search for I can find. It will also be very hard on the cluster if users will be retrieving such large sets of data simultanously. The best/nicest option is to use the pagination functionality in Elastic Search. This means that the buttons in the view, will be retrieving the 'next' page of data from Elastic Search. This way, ES returns only 10 results per page as it should. But then the problem is that the SortTable.jsx only filters/sorts those 10 instead of possibly all user projects (the SortTable doesn't know what is in Elastic Search potentially).

**Comment by jwassenaarbg** [comment]
Actually, maybe I can do a first query without actually returning data, just to get the number of hits. And then set the size parameter of the real query to that number. This way all will be returned instead of a hard limit of for example 1000. Still, if users really have a large number of projects it would maybe result in a performance issue.

**Comment by jblom** [comment]
just to confirm that indeed we haven't implemented paging in the workspace API yet. Not even changing the amount of results I think. So let's do that first. Then we can test if we do paging on the client side or always call the server.

**Comment by jblom** [comment]
ok I fixed the workspace API. By default it now returns the first 250 projects (per user). The media suite already takes care of paging/searching through these 250 entries on the client side, so it should work fine. I've deployed this on test.

**Comment by lilimelgar** [comment]
Great! Tested in master.
