### ISSUE TITLE
As a scholar, I want to be able to filter the KB data per date

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#292]
Jaap re-indexes KB data in the production version on test and fixes the mapping. After that, the collection can be reindexed in production with the new mappings.

At least should work for a substantial part of data.

**Comment by jblom** [comment]
Ah I found the reason that dates did not seem to work before: 

the dc:date is only attached to Newspaper objects/results and because you mostly don't find any newspapers given your search term - the only text fields a newspaper has is the title, which is the name of the newspaper - selecting a date field for filtering will mostly result in "No data found for this date field"

@wmelder @roelandordelman I'd say in this case it's better to create a derivative index just like the aggregate index for B&G (as we talked about earlier). It just does not work nicely for facet search (having separate documents for things that belong together)
