### ISSUE TITLE
As a scholar I want to view the personal file I uploaded in the workspace in the resource viewer

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#335]

**Comment by jblom** [comment]
@jwassenaarbg & @roelandordelman I worked on this and it already works on master. There is one more aeastetic thing I want to fix and then I'll also deploy this to test.

**Comment by jblom** [comment]
@roelandordelman @lilimelgar @jwassenaarbg I also tested a bit with dropbox and it seems you can only play items from your own dropbox, because when embedding a dropbox link you see how dropbox uses cookies to check who is trying to embed & play it. 

I guess this is fair enough, since it will prevent the possibility that dropbox becomes a free streaming platform.

The dropbox link are however perfectly fine for downloading & enriching! It's just that the in-browser play-out is restricted to you being logged in to the dropbox account.

**Comment by lilimelgar** [comment]
I have tested in the master (clariah_test account) with different options, including a Youtube link, Google drive link, and Dropbox link. I get the message: "Either you are not allowed access or this item does not exist" when I try to play the resource. @jwassenaarbg or @jblom: help, please: What am I missing? ;)

**Comment by jblom** [comment]
@lilimelgar did you also update the media suite?
