### ISSUE TITLE
As a user, I need to bookmark items from different pages in the search results without having to save them per page

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#423]
Currently, users can bookmark several items in the result list by selecting them in a page, then saving them to a project, then going to another page. They would like the selection to be remembered when changing to a different page in the result list: bookmark selector should remember which pages you selected (now these selections seem to be lost when going to another page in the search results).

See also #422 (any of the two solutions would work for the purpose).

**Comment by lilimelgar** [comment]
@jblom This issue was still important/requested by users during the Summer school.

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 
Branch : task/#423-remember-bookmarked-selections 
Now every bookmarked item in SingleSearch is kept between different result pages unless the user updates the query or via the dropdown menu decides to clear all selected items or save them.
Also is possible for the via a dropdown menu to take 3 actions:
Bookmark the selected items;
Clear the current selection;
Show current bookmarked items

The icon for bookmarking has also been update from the star to the bookmark icon since it's what's called in the Workspace.

Also along with this issue there was an issue when selecting items in collections other than BenG. Only the first item was affected by selecting any checkbox from the result list. Cause:
The function only considered the BenG format and in any other case it returns empty/null which make every id the same. The solution is not the most elegant (|| resourceId) but it solves the issue.

safeModalId(resourceId) {
return resourceId.substr(0, resourceId.indexOf('@')) + '__modal';
}

**Comment by avlisodraude** [comment]
@jblom, @lilimelgar : issue regarding not implemented "check all " option for paging is solved. 
The selected options box has been styled based on Liliana and Hugo suggestions, ie, setting max-height, scrolling if needed, hide current page results when previewing results.

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I've checked this out and merged with master. It's really nice to be able to bookmark across multiple pages. Love the dropdown and "show selection view" etc. I'd say this is solved

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #178](https://github.com/beeldengeluid/labo-components/issues/178) via [**ZenHub**](https://www.zenhub.com/)
