### ISSUE TITLE
As a developer, I need to fix problem with size of long labels for facets

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#494]
Currently, the label for the new facets (Search tool) is taken by using the default field labels. Sometimes, these are quite long. The display currently goes to the next line of the facet box. Ideally, the text should be resized or adapt the space for the label to fit its size.

![Screen Shot 2018-08-14 at 11.21.29.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/e1f95276-278b-4a67-b482-466944cb8125)

![screen shot 2018-08-14 at 11 26 16](https://user-images.githubusercontent.com/8133228/44083646-e6a69922-9fb4-11e8-8a2f-d16dd6b6d128.png)

**Comment by avlisodraude** [comment]
@lilimelgar  @jblom 
Issue done on branch "task/#494-long-size-facet-labels" in the labo-components project.
https://github.com/beeldengeluid/labo-components/pull/114

The solution is css only consisting in truncating long texts with ellipsis (...).
Since hovering over the title displays the complete name of the field no information is lost. 
Some re-styling was applied as well to make the labels more consistent with the rest of the layout.

![Screen Shot 2018-08-16 at 16.54.43.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/2a177f6d-acf3-4c8d-92d5-b174011e0de4)

**Comment by lilimelgar** [comment]
@jblom I tested this on the branch above for several collections and it works well. However, since the format of the labels for B&G in the Create new facet component is different than in the Inspector tool, the labels will mostly show the level:

![screen shot 2018-08-21 at 09 42 06](https://user-images.githubusercontent.com/8133228/44388006-54370680-a527-11e8-8b5d-ce43b74e6c67.png)

I will test this again when issue #486 is solved.

**Comment by lilimelgar** [comment]
Tested in test version, fixed.
