### ISSUE TITLE
As a developer, I need to fix bug in the annotation/workspace API call when user deletes annotations

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#500]
When a user deletes an annotation other bookmarks/segments are deleted (perhaps all related to the same bookmark group).

**Comment by jblom** [comment]
almost done with this one. Will deploy it this morning, so it can be tested. Basically this bug was a sign that it was time to move the complicated "annotation/bookmark assembling & reconsiliation logic" from the client to the server. This means now the annotation API directly calls the search API to reconsile the resource IDs with the metadata. Also the annotation API makes sure the client can directly ask for a list of bookmarks or annotations without needing to further process it.

**Comment by jblom** [comment]
@lilimelgar so I've deployed the new stuff on test. You can test it now. If you want to run locally check out these branches:

labo -> no_reconsile
ms -> new_annotation_api

Also I now made deleting a big list of annotations/bookmarks much smoother, since it now takes the browser a single request to delete them all (instead of one for each one selected).

In fact: the old way was really unreliable, since it would happen often that not the entire selection was deleted... (so it required the user to try multiple times)

Anyway. Please test and let me know how it works. I will look a bit more at it tomorrow to make sure it's indeed good enough

**Comment by jblom** [comment]
@lilimelgar actually I merged both branches with master, so you can just use that

**Comment by lilimelgar** [comment]
@jblom Great to see all these improvements! 

On the test, Master version, there are some initial issues:
See screencast for these two [here](https://drive.google.com/file/d/1QhzQtJifpg7Ymt5Du8e9vwNd2BuxWCaZ/view?usp=sharing):
-[ ] When assigning a term (classification, from GTAA) to a Resource, two annotations are created instead of one
-[ ] When going back to the Resource to check its annotations, these don't show in the annotation list, but you can see the initial annotation if you click on "Annotate resource". 

I have detected other issues in the Workspace, but perhaps checking this one first would solve the others?

**Comment by jblom** [comment]
@lilimelgar thanks for reporting, that one I never noticed. Going to look at it right away

**Comment by jblom** [comment]
@lilimelgar been working on this today and might have already solved it (spent quite some time doing another refurbishment cycle, so cleaned up a lot of complicated crap). You could test in the branch annotation_targetting (labo)

Also found why the merging of e.g. classifications (annotation-centric view) does not work properly. Will solve this next week.

**Comment by jblom** [comment]
@lilimelgar I've worked on the two things you detected and they should be solved. Also I've fixed the problem with the annotation-centric classification view. Now all related bookmarks/media objects items are properly listed with each classification (other types should work as well)

Please test

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #180](https://github.com/beeldengeluid/labo-components/issues/180) via [**ZenHub**](https://www.zenhub.com/)
