### ISSUE TITLE
As a developer, I need to fix issue with bookmark ordering options in the Workspace

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#515]
This issue has two parts:

- [ ] Bug. Fix issue with ordering options: the bookmarks in the workspace (user project) can be ordered accordingly to different criteria. There seems to be a problem though when switching between options (the first selected option sticks). See [screencast](https://drive.google.com/open?id=1f1Zn5HdkdTWuW68csJI7JiZRKhAcXC1o).

- [ ] Display the "Bookmark creation date" in the bookmark list above.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
issues (so far): 
Table default sorting to "Bookmark created" (for which there is no column available) so it lead users to believe that the DATE column is the one affected by this sorting (DATE = record created). 

Maybe this default sorting can be removed from the 'selection list' since user can sort by group or other criteria already available?

"MEDIA" column sorting breaks when no media value is present in record showing a Javascript error (BookmarkTable.jsx:248 Uncaught TypeError: Cannot read property 'length' of undefined)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #173](https://github.com/beeldengeluid/labo-components/issues/173) via [**ZenHub**](https://www.zenhub.com/)
