### ISSUE TITLE
As a scholar, I want to have nice icons, instead of tool screenshots on the tools page

### ISSUE THREAD

**Issue by jblom** [CLARIAH/wp5_mediasuite#519]
Story title says it all. Please figure out a way to get nice big icons like FW provided.

The order should be:

Inspect, Search, Compare, Explore

**Comment by avlisodraude** [comment]
Tool icons modified and styling updated to avoid current issues with different size resolutions (seeing 3 items in a row when resizing ).
Since this is a more subjective issue regarding 'done' I just set it to test. 
Please  add any comments :-)
branch in wp5 project:
task/#519-add-icons-for-tools-a

**Comment by jblom** [comment]
@avlisodraude I actually already merged this one with master as I guess it's already nicer that the silly screenshots. When @roelandordelman approves we can close this issue
