### ISSUE TITLE
Adding new facets

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#56]
When you try to add certain facets there is no reaction (the facet is not added), as far as I could test, this happens mostly when the facet was already added or when you forget to add a label to the facet, or when you press enter instead of "add". In one case I could not find a reason (collection: Heropvoeding jeugdige politieke delinquenten, adding genre facet. Also, in some cases adding the "temporal: mods: subject" does not work). Perhaps add text saying: "this facet is added already" and/or "check your facet selection"?

**Comment by jblom** [comment]
this should be solved now too. Right now the 'desired facets' are leading, instead of the actually found facets. This means you always get an extra tab whenever you add a new facet. This also means that it is possible to get a facet tab without any results, because it is possible that there are simply no results for the facet (aggregation) you desire to create. (ok I could explain this better, but I hope you understand)
