### ISSUE TITLE
Histogram colors/interaction

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#59]
Users tend to click on the bars in the histogram and on the dots in the timeline chard (#83). The expected behavior is that these bars and dots will bring the results for that query for that year, most likely via a pop-up. If not possible: add tooltip indicating that users should refine their date range selection to that year to obtain the filtered results.

**Comment by jblom** [comment]
I wanted to make them clickable, so you can refine your search to a single year, but I'll finish this later since now the result will be 1) a time slider with not enough data (because 1 year is selected) 2) a histogram with just one big bar.

The overall solution would be to be able to always see the timeslider+histogram with the full range of dates/years whether you've made a selection (of dates/years) or not. This however can take some time and I want to pick this up for v2 (if desired).

**Comment by lilimelgar** [comment]
I included this in the issues for MSV1 evaluation, will provide input on requirements after that. Added to V2 milestone and closed for now.

**Comment by lilimelgar** [comment]
See also issue #82

**Comment by lilimelgar** [comment]
@avlisodraude This is still requested by users..
