### ISSUE TITLE
Flow: Going back from (search) recipe to Collection inspector recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#62]
If you start by using Collection exploration recipe, after you send a collection to a search recipe, there is no way to go back to the collection exploration task you were doing.

**Comment by jblom** [comment]
it does remember the collections you've selected, it does not remember the collection analysis parameters you have filled in. I'd say this is for v2, since we need to properly think about the exact purpose of the collection exploration recipe. (so also: what data should be sharable with others and thus should be reflected in the URL)

**Comment by lilimelgar** [comment]
I added label "requirements" to indicate we need a "design session". Also requested in Gitter (May 15)

**Comment by lilimelgar** [comment]
This issue became obsolete. New redesign is needed for supporting workflows.
