### ISSUE TITLE
Retrieval of too few results in Multi-layered single collection search recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#64]
Why there are only 2 results when I search for "voetballen" in the "collecion metadata" layer? using the current "single collection search" recipe for B&G collection.

**Comment by lilimelgar** [comment]
Also, when I search with the term "journaal" in the "collection metadata" option, there are only two genres in the "Genre facet", is this correct?

**Comment by jblom** [comment]
The single search recipe was configured to use another kind of index for B&G: one that has all the annotation layers. The issue was that this index only has records for annotated items/programs. The rest is not in there. 

Now I switched the single search to the regular B&G index and all items should be in there.

The layered search is for v2 or v3

**Comment by lilimelgar** [comment]
We will have to look at this again (requirements), and also write explanation in the guidelines (action taken).

**Comment by lilimelgar** [comment]
This issue is replaced by #109
